from pymongo import MongoClient, errors
import os

def connect_to_mongo():
    """Conecta a MongoDB local o usando MONGO_URI"""
    try:
        mongo_uri = os.getenv("MONGO_URI", "mongodb://localhost:27017/")
        client = MongoClient(mongo_uri, serverSelectionTimeoutMS=5000)
        client.admin.command('ping')  # Prueba r√°pida de conexi√≥n
        print("‚úÖ Conexi√≥n exitosa a MongoDB")
        return client["gesmin"], client  # Devuelvo tambi√©n el objeto cliente para cerrarlo despu√©s
    except errors.ConnectionFailure as e:
        raise RuntimeError(f"‚ùå No se pudo conectar a MongoDB: {str(e)}")

def insert_json_in_collection(db, collection_name, json_data):
    """Inserta un JSON en la colecci√≥n"""
    try:
        collection = db[collection_name]
        result = collection.insert_one(json_data)
        print(f"üóÑÔ∏è Insertado en {collection_name} con ID: {result.inserted_id}")
        return result.inserted_id
    except Exception as e:
        raise RuntimeError(f"‚ùå Error al insertar en MongoDB: {str(e)}")